version: '3'

services:
  web:
    restart: always
    build: ./web
    command: gunicorn crowdFunding.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./web/media/static:/django_ec2/web/media/static
    expose:
      - "8000"
    
  nginx:
    restart: always
    build: ./nginx/
    volumes:
      - ./web/media/static:/static
    ports:
      - "80:80"
    
